version: '3'
services:
    laravel:
        container_name: 'laravel'
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: sail-8.2/app
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 2048M
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8003:80'
            - '5176:5173'
        environment:
            WWWUSER: 1000
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        restart: unless-stopped
        volumes:
            - '.:/var/www/html'
        networks:
            - laravel-net
        depends_on:
            - laravelDB

    laravelDB:
        container_name: 'laravelDB'
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3311:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        restart: unless-stopped
        volumes:
            - 'laravel-mysql:/var/lib/mysql'
        networks:
            - laravel-net
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    laravel-net:
        driver: bridge
volumes:
    laravel-mysql:
        driver: local